name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarScanner CLI
        uses: actions/cache@v3
        with:
          path: ~/.sonar/scanner
          key: sonarscanner-cli-${{ hashFiles('**/pom.xml') }}

      - name: Install SonarScanner CLI
        run: |
          mkdir -p ~/.sonar/scanner
          cd ~/.sonar/scanner
          SCANNER_FILE_NAME=sonar-scanner-cli-7.0.2.4839-linux-x64.zip
          wget --no-verbose --user-agent=sonarqube-scan-action https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/$SCANNER_FILE_NAME 
          unzip -q -o $SCANNER_FILE_NAME
          mv -f sonar-scanner-7.0.2.4839-linux-x64/bin/sonar-scanner /usr/local/bin/

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}